version: '3'


services:
  i2p_spider:
    restart: always
    image: chongrufan/spider_i2p_browser:v2
    container_name: spider_i2p_browser
    # 直接host模式
    ports:
      - 21106:21106
      - 21106:21106/udp
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
    # 将下列文件进行挂载
    # 1. 配置文件config
    # 2. 数据文件（流量、流日志）
    # 3. 日志文件
    # 4. 根目录
    volumes:
      - "/home/ubuntu/aimafan/collect_i2p_browser/config:/app/config"
      - "/home/ubuntu/aimafan/collect_i2p_browser/data:/app/data"
      - "/home/ubuntu/aimafan/collect_i2p_browser/logs:/app/logs"
      - "/root:/root"
    # 设置特权模式
    privileged: true